### PR TITLE
ISSUE-238 Scenarios for the acquisition of data files and file versioning

### PR DESCRIPTION
**Pull request by lewismc**
WIP for https://github.com/tagbase/tagbase-server/issues/238 and https://github.com/tagbase/tagbase-server/issues/164
Work to be done
* rather than concatenating the `dataset_id` as a string and including in `submission` table, we should create a new foreign key `dataset_id` in `submission` referencing `dataset` table.
* it is OK to open file twice (as long as we only read metadata). We need to create functions to 1. only read the global attributes (metadata) and 2. populate the `dataset` table, and 3. ensure that the `dataset_id` is populated in `submission`.

### CODE REVIEW

**Comment by lewismc** [comment]
More work to be done here @renato2099 but we are pretty close.

**Comment by renato2099** [comment]
hey @lewismc , I pushed a WIP commit about moving from a trigger based data migration to a stored-procedure one, but before we go down that path I'd like us to do some additional validation and think through if we want this potentially large behavioural change at this point

**Comment by renato2099** [comment]
hey @lewismc  I run a couple of ingestions with this patch and it seems to be doing something 😅  I see data being ingesting but we should check if data migration is still working as expected before we proceed with this

**Comment by lewismc** [comment]
Hi @renato2099 I updated this patch and have tested it. It looks good. I will note the following things though
* upon ingestion of `iccat_gbyp0008_ArgosTrans_eTUFF0.txt` and successful migration, loads of data is left in `proc_observations`... this requires investigation
* we need more unit tests
* for some reason the result of a `GET` on `/tags/{tag_id}` now returns the same metadata for each submission rather than different metadata. I checked and confirmed that the correct metadata is populated into the database so this is definitely a bug in [tags_controller.py](https://github.com/tagbase/tagbase-server/blob/main/tagbase_server/tagbase_server/controllers/tags_controller.py#L61-L99)
* we need to augment the stored procedure to accommodate the following scenario

> User initially ingests a tag submission representing a reference track. User then ingests a different file which is for the same tag and dataset but the _new_ reference track. We need to make sure that the original submission and the metadata is no longer the reference track. This is a kinda tricky as essentially the sha256 needs to change as well.

* finally,

**Comment by lewismc** [comment]
@renato2099 I updated this PR to fix # 3 above. This was an old bug which we hadn't caught before. It is now fixed.

**Pull request merged**
