### PR TITLE
Refactoring for reducing number of queries

### PR DESCRIPTION
**Pull request by renato2099**
@lewismc this is a small refactoring such that in a second stage we can reduce the number of queries when checking global variables, i..e, instead for 1 SQL query per global attribute we can try to have just a few queries instead.
Another advantage is that we can batch the slack messages related to the metadata processing.

### CODE REVIEW

**Comment by renato2099** [comment]
I will add unit tests for the new two methods once we agree on the current refactoring.
I am not sure though if the indentation change shows up as new code being added ? do you know @lewismc ?

**Comment by lewismc** [comment]
Excellent @renato2099 lets go through this tomorrow. I think this can be merged in after the PR for #181

**Comment by lewismc** [comment]
I refactored the slack calls. Let's test out on Thursday.

**Comment by renato2099** [comment]
Hey @lewismc I added a few unit tests I think we should merge this

**Review by lewismc — APPROVED** [review]
+1 I have tested locally and all checks out. Tox tests pass for Python 3.9 and 3.10 locally and also the CI testing passes successfully. I will open  a follow on ticket with something i noticed.

**Pull request merged**
